
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class CreateStudent extends javax.swing.JFrame {

    /**
     * Creates new form CreateStudent
     */
    
    String path1;
    File f=null;
    StudentFunction sf;
    public CreateStudent() {
        
        initComponents();
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton1);
        bg.add(jRadioButton2);
       jRadioButton1.setSelected(true);
       
       JPanel panel = new JPanel();
       panel.setBounds(1230, 187, 189, 206);
       jPanel1.add(panel);
       
       JButton btnNewButton = new JButton("Image");
       btnNewButton.setIcon(new ImageIcon(CreateStudent.class.getResource("/image/image.png")));
       btnNewButton.addActionListener(new ActionListener() {
       	public void actionPerformed(ActionEvent e) {
       	}
       });
       btnNewButton.setFont(new Font("Times New Roman", Font.PLAIN, 25));
       btnNewButton.setBounds(1254, 412, 149, 29);
       jPanel1.add(btnNewButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBounds(305, 10, 835, 98);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(130, 161, 70, 29);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(130, 206, 87, 29);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(130, 245, 207, 29);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(130, 298, 207, 29);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setBounds(130, 350, 177, 29);
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setBounds(130, 496, 87, 29);
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setBounds(130, 550, 120, 29);
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setBounds(130, 623, 250, 29);
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setBounds(150, 849, 189, 29);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBounds(417, 158, 653, 35);
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setBounds(417, 203, 653, 35);
        jTextField3 = new javax.swing.JTextField();
        jTextField3.setBounds(417, 248, 653, 35);
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setBounds(417, 295, 653, 35);
        jTextField6 = new javax.swing.JTextField();
        jTextField6.setBounds(417, 489, 653, 43);
        jTextField8 = new javax.swing.JTextField();
        jTextField8.setBounds(417, 542, 653, 45);
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(417, 606, 653, 46);
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setBounds(417, 840, 653, 51);
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton2.setBounds(1160, 850, 130, 40);
        jButton3 = new javax.swing.JButton();
        jButton3.setBounds(1490, 850, 120, 37);
        jButton4 = new javax.swing.JButton();
        jButton4.setBounds(1640, 850, 130, 37);
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser1.setBounds(417, 340, 653, 46);
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setBounds(130, 410, 87, 29);
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton1.setBounds(422, 406, 111, 37);
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton2.setBounds(718, 406, 155, 37);
        jButton5 = new javax.swing.JButton();
        jButton5.setBounds(1320, 850, 140, 41);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(0, 128, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new Font("Times New Roman", Font.BOLD, 36)); // NOI18N
        jLabel1.setText("High School Management System");

        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Create New Student Profile");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(178, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 520, GroupLayout.PREFERRED_SIZE)
        					.addGap(137))
        				.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 372, GroupLayout.PREFERRED_SIZE)
        					.addGap(213))))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel1.add(jPanel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID :");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name :");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Father's Name :");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mother's Name :");
        jPanel1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of Birth :");
        jPanel1.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Class :");
        jPanel1.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone :");
        jPanel1.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Permanent Address");
        jPanel1.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("current address");
        jPanel1.add(jLabel11);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField1);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField2);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField3);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField4);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField8);

        jPanel1.add(jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save-icon (1).png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/View-icon.png"))); // NOI18N
        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jDateChooser1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (3).png"))); // NOI18N
        jButton5.setText("Menu");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file-info-icon.png"))); // NOI18N
        jMenuItem2.setText("Teacher file");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file-info-icon.png"))); // NOI18N
        jMenuItem3.setText("Result file");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file-info-icon.png"))); // NOI18N
        jMenuItem5.setText("Class file");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (3).png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-icon.png"))); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
        jlabel_photo = new javax.swing.JLabel();
        
                jlabel_photo.setBackground(new java.awt.Color(51, 51, 0));
                jlabel_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jButton1 = new javax.swing.JButton();
        
                jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image.png"))); // NOI18N
                jButton1.setText("Image");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 1549, GroupLayout.PREFERRED_SIZE)
        			.addGap(38)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jlabel_photo, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(214)
        					.addComponent(jlabel_photo, GroupLayout.PREFERRED_SIZE, 223, GroupLayout.PREFERRED_SIZE)
        					.addGap(131)
        					.addComponent(jButton1))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 817, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(73, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
      
       if(!Character.isDigit(evt.getKeyChar()))
      {
          evt.consume();
      }
        
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        try {
        String name=jTextField2.getText();
        String fname=jTextField3.getText();
        String mname=jTextField4.getText();
        String par_addres=jTextArea1.getText();
        String cur_addres=jTextArea2.getText();
        String gender="Male";
        String phone=jTextField8.getText();
//        try {
        int sclass=Integer.valueOf(jTextField6.getText());
        int id=Integer.valueOf(jTextField1.getText());
//        } catch (NumberFormatException e) {
//           /// JOptionPane.showMessageDialog(null,e);
//        }
     
        if(jRadioButton2.isSelected())
        {
            gender="Female";
        }
  if(verifyText())
   {
            
        SimpleDateFormat dateForm=new SimpleDateFormat("yyyy-MM-dd");
        String bdate=dateForm.format(jDateChooser1.getDate());
       try {
            FileInputStream fin=new FileInputStream(f);
           int len=(int)f.length(); 
//         StudentFunction std=new StudentFunction();
//        std.insertUpdateDelete('i', id, name, fname, mname, bdate,sex, sclass,phone, par_addres, cur_addres,fin,len);
//        Connection con=myConnection.getConnection();
          
        Connection con=AllConnection.getConnection();    

         
        PreparedStatement ps;
//        if(operation=='i')
//        {
            try {
                
                ps=con.prepareStatement("INSERT INTO `student_info`(`id`, `name`, `father`, `mather`, `dob`, `gender`, `class`, `phone`, `par_address`, `cur_address`,`image`) "
                        + "VALUES (?,?,?,?,?,?,?,?,?,?,?)");
                  
                 ps.setInt(1, id);
                 ps.setString(2, name);
                 ps.setString(3, fname);
                 ps.setString(4, mname);
                 ps.setString(5,bdate);
                 ps.setString(6, gender);
                 ps.setInt(7, sclass);
                 ps.setString(8,phone);
                 ps.setString(9,par_addres);
                 ps.setString(10, cur_addres);
                 ps.setBlob(11,fin,len);
               
                 if(ps.executeUpdate()>0)
                 {
                     JOptionPane.showMessageDialog(null,"new student data added");
                 }
                 else
                     JOptionPane.showMessageDialog(null,"new student data not added");
            }
                 catch (SQLException ex) {    
                /// JOptionPane.showMessageDialog(null,"add failed");
                 JOptionPane.showMessageDialog(null,ex);
            }
//        }
        /////   std.insertUpdateDelete(, len, name, fname, mname, bdate, bdate, len, phone, par_addres, cur_addres, fin, len);
       } catch (FileNotFoundException ex) {
         JOptionPane.showMessageDialog(null,ex);
       }
           
      
        
     }
        } catch (HeadlessException | NumberFormatException e) {
           JOptionPane.showMessageDialog(null,"one or more field emtry");
        }
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        try {
               JFileChooser fc=new JFileChooser();
               fc.showOpenDialog(this);
               f=fc.getSelectedFile();
               String path=f.getAbsolutePath();
               ImageIcon Myimage=new ImageIcon(path);
               Image img=Myimage.getImage();
               Image newImage=img.getScaledInstance( jlabel_photo.getWidth(), jlabel_photo.getHeight(),Image.SCALE_SMOOTH);
               jlabel_photo.setIcon(new ImageIcon(newImage));
//              jlabel_photo.setIcon(new ImageIcon(path));
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jTextField2.setText("");
       jTextField3.setText("");
        jTextField4.setText("");
        jTextArea1.setText("");
       jTextArea1.setText("");
        jTextArea2.setText("");
       jTextField8.setText("");
      jTextField6.setText("");
      jTextField1.setText("");
//      SimpleDateFormat dateForm=new SimpleDateFormat("yyyy-MM-dd");
//      String bdate=dateForm.format(jDateChooser1.setDate());
       jDateChooser1.setDate(null);
       jRadioButton1.setSelected(true);
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                           StudentView form=new StudentView();
                           form.setVisible(true);
                           form.setLocationRelativeTo(null);
                            
                           form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                           dispose(); 
                          form.jLabel2.setText("Total records :"+Integer.toString(StudentFunction.countRecord("student_info")));
                           try {
                              sf.fillStudentJtable(StudentView.jTable1, "");
        } catch (Exception e) {
             /// JOptionPane.showMessageDialog(null,e);
        }
                          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        
                         StudentClass form=new StudentClass();
//                       form.setDefaultCloseOperation(null);
                         form.setVisible(true);
                         form.setLocationRelativeTo(null);
//                       form.dispose();
                         form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                         dispose();
                         form.setResizable(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                           ManuClass form=new ManuClass();
                           form.setVisible(true);
                           form.setLocationRelativeTo(null);
                     
                          //form.setSize(600,600);
                           ///form.setExtendedState(JFrame.MAXIMIZED_BOTH);
                           form.welcome.setText("Wecome Mr "+jTextField1.getText());
                           dispose();
                           form.setResizable(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
                           TeacherClass form=new  TeacherClass();
//                         form.setDefaultCloseOperation(null);
                           form.setVisible(true);
                           form.setLocationRelativeTo(null);
//                         form.dispose();
                           form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                           dispose();
                          form.setResizable(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                        ResultClass form=new  ResultClass();
//                         
                           form.setVisible(true);
                           form.setLocationRelativeTo(null);
//                        form.dispose();
                           form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                           form.setResizable(false);
                           dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       
                            ClassMain form=new ClassMain();
//                           form.setDefaultCloseOperation(null);
                           form.setVisible(true);
                           form.setLocationRelativeTo(null);
//                          form.dispose();
                          form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                           form.setResizable(false);
                           dispose();
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
   public boolean verifyText()
  {
       
        if(jTextField1.getText().equals("")|| jTextField2.getText().equals("") ||jTextField3.getText().equals("") ||  jTextField4.getText().equals("") || jDateChooser1.getDate()==null || jTextField6.getText().equals("")|| jTextField8.getText().equals("")|| jTextArea1.getText().equals("")||jTextArea2.getText().equals(""))
        {
              JOptionPane.showMessageDialog(null,"one or more emtry field");
               return false;
        }
        /// choose a date higher than the current date
        else if(jDateChooser1.getDate().compareTo(new Date())>0)
        {
             JOptionPane.showMessageDialog(null,"invalid date");
             return false;
        }
       else
        return true;
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel jlabel_photo;
}
