import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;


public class StudentUpdate extends javax.swing.JFrame {

    /**
     * Creates new form StudentUpdate
     */
    StudentFunction s=new StudentFunction();
    DefaultTableModel model;
    File f=null;
    public StudentUpdate() {
        initComponents();
        s.fillStudentJtable(jTable1,"");
//         ButtonGroup bg=new ButtonGroup();
//         bg.add(male);
//         bg.add(female);
//        model=(DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.red);
        jTable1.setSelectionBackground(Color.blue);
        
        btnNewButton = new JButton("Save");
        btnNewButton.setIcon(new ImageIcon(StudentUpdate.class.getResource("/image/Save-icon (1).png")));
        btnNewButton.setFont(new Font("Times New Roman", Font.PLAIN, 25));
        btnNewButton.setBounds(121, 694, 150, 47);
        jPanel1.add(btnNewButton);
        
        btnNewButton_1 = new JButton("Menu");
        btnNewButton_1.setIcon(new ImageIcon(StudentUpdate.class.getResource("/image/StartMenu.png")));
        btnNewButton_1.setFont(new Font("Times New Roman", Font.PLAIN, 25));
        btnNewButton_1.setBounds(332, 692, 178, 50);
        jPanel1.add(btnNewButton_1);
        
        btnNewButton_2 = new JButton("Cancel");
        btnNewButton_2.setIcon(new ImageIcon(StudentUpdate.class.getResource("/image/cancel.png")));
        btnNewButton_2.setFont(new Font("Times New Roman", Font.PLAIN, 25));
        btnNewButton_2.setBounds(598, 692, 155, 50);
        jPanel1.add(btnNewButton_2);
        
//        JScrollPane jsp=new JScrollPane(jTable1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBounds(332, 10, 910, 120);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(20, 210, 70, 29);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(20, 270, 70, 29);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(20, 330, 155, 29);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(20, 400, 164, 29);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setBounds(21, 439, 154, 29);
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setBounds(20, 534, 70, 29);
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setBounds(20, 593, 75, 29);
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setBounds(21, 647, 160, 29);
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setBounds(20, 810, 150, 29);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBounds(200, 210, 370, 35);
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setBounds(200, 260, 370, 35);
        jTextField3 = new javax.swing.JTextField();
        jTextField3.setBounds(200, 320, 370, 35);
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setBounds(200, 390, 371, 35);
        jTextField6 = new javax.swing.JTextField();
        jTextField6.setBounds(200, 534, 380, 35);
        jTextField8 = new javax.swing.JTextField();
        jTextField8.setBounds(200, 585, 380, 35);
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBounds(200, 647, 380, 35);
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setBounds(200, 810, 380, 40);
        jTextArea2 = new javax.swing.JTextArea();
        jlabel_photo = new javax.swing.JLabel();
        jlabel_photo.setBounds(620, 210, 208, 207);
        jButton1 = new javax.swing.JButton();
        jButton1.setBounds(630, 428, 190, 50);
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser1.setBounds(200, 435, 370, 35);
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setBounds(20, 478, 87, 29);
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton1.setBounds(200, 490, 111, 37);
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton2.setBounds(402, 490, 155, 37);
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane3.setBounds(838, 160, 664, 551);
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton3.setBounds(260, 870, 220, 50);
        jButton4 = new javax.swing.JButton();
        jButton4.setBounds(520, 870, 150, 50);
        jButton5 = new javax.swing.JButton();
        jButton5.setBounds(710, 870, 140, 50);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(0, 128, 128));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new Font("Times New Roman", Font.BOLD, 40)); // NOI18N
        jLabel1.setText("High School Management System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Update Student Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(223)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 444, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(243, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        			.addContainerGap(186, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 589, GroupLayout.PREFERRED_SIZE)
        			.addGap(135))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addGap(99))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel1.add(jPanel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Father Name");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mother Name");
        jPanel1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of Birth");
        jPanel1.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Class");
        jPanel1.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("phone");
        jPanel1.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("per address");
        jPanel1.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("cur address");
        jPanel1.add(jLabel11);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField1);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField2);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField3);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(jTextField4);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField8);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);

        jlabel_photo.setBackground(new java.awt.Color(51, 51, 0));
        jlabel_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        jPanel1.add(jlabel_photo);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image.png"))); // NOI18N
        jButton1.setText("Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jDateChooser1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gender");
        jPanel1.add(jLabel12);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "Fname", "Mname", "Dob", "Gender", "Class", "phone", "par_addr", "cur_addr", "image"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable1MouseExited(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3);
        jButton2.setBounds(80, 870, 141, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Editicon.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/StartMenu.png"))); // NOI18N
        jButton3.setText("Student Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (3).png"))); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel.png"))); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file-info-icon.png"))); // NOI18N
        jMenuItem2.setText("Teacher file");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file-info-icon.png"))); // NOI18N
        jMenuItem3.setText("Result file");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file.png"))); // NOI18N
        jMenuItem6.setText("Class file");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home-icon (3).png"))); // NOI18N
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete-icon.png"))); // NOI18N
        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 1540, Short.MAX_VALUE)
        			.addGap(18))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 961, GroupLayout.PREFERRED_SIZE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

                try {
                        JFileChooser fc=new JFileChooser();
                        fc.showOpenDialog(this);
                        f=fc.getSelectedFile();
                        String path=f.getAbsolutePath();
                        jlabel_photo.setIcon(new ImageIcon(path));
                    } catch (HeadlessException e){
                        System.out.println(e);
                    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int rowIndex=jTable1.getSelectedRow();
        model=(DefaultTableModel) jTable1.getModel();
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        if(model.getValueAt(rowIndex, 5).toString().equals("Male"))
        {
            jRadioButton1.setSelected(true);
        }
        else
        {
            jRadioButton2.setSelected(true);
        }
        jTextField1.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField2.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField3.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField4.setText(model.getValueAt(rowIndex, 3).toString());
        jTextField6.setText(model.getValueAt(rowIndex, 6).toString());
        jTextField8.setText(model.getValueAt(rowIndex, 7).toString());
        jTextArea1.setText(model.getValueAt(rowIndex, 8).toString());
        jTextArea2.setText(model.getValueAt(rowIndex, 9).toString());
        //// jlabel_photo.setBlob(model.getValueAt(rowIndex, 10));
        try {
           
            Connection con=AllConnection.getConnection();
            Statement st=con.createStatement();

            ResultSet rs=st.executeQuery("SELECT * FROM `student_info` WHERE `id`='"+jTextField1.getText()+"'");
            if(rs.next())
            {
                byte[] img=rs.getBytes("image");
                try {
                     ImageIcon image=new ImageIcon(img);
                     Image im=image.getImage();
                // Image myImg=im.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_REPLICATE);
                // ImageIcon newImage=new ImageIcon(myImg);
                     ImageIcon newImage=new ImageIcon(im);
                       jlabel_photo.setIcon(newImage);
                } catch (Exception e) {
                    
                }
               
            }
            else
            {
                JOptionPane.showMessageDialog(null,"no data");

            }

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        Date bdate;
        try {
            bdate=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooser1.setDate(bdate);
        } catch (ParseException ex) {
            /// Logger.getLogger(manageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseExited
        
    }//GEN-LAST:event_jTable1MouseExited

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
         if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN)
        {   
        int rowIndex=jTable1.getSelectedRow();
        model=(DefaultTableModel) jTable1.getModel();
       jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
       if(model.getValueAt(rowIndex, 5).toString().equals("Male"))
        {
            jRadioButton1.setSelected(true);
            jRadioButton2.setSelected(false);
        }
        else
        {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(true);
        }
         jTextField1.setText(model.getValueAt(rowIndex, 0).toString());
         jTextField2.setText(model.getValueAt(rowIndex, 1).toString());
         jTextField3.setText(model.getValueAt(rowIndex, 2).toString());
         jTextField4.setText(model.getValueAt(rowIndex, 3).toString());
         jTextField6.setText(model.getValueAt(rowIndex, 6).toString());
         jTextField8.setText(model.getValueAt(rowIndex, 7).toString());
         jTextArea1.setText(model.getValueAt(rowIndex, 8).toString());
         jTextArea2.setText(model.getValueAt(rowIndex, 9).toString());
        //// jlabel_photo.setBlob(model.getValueAt(rowIndex, 10));
         try {
          
            
            Connection con=AllConnection.getConnection();
            Statement st=con.createStatement();
         
           ResultSet rs=st.executeQuery("SELECT * FROM `student_info` WHERE `id`='"+jTextField1.getText()+"'");
           if(rs.next())
           {
               byte[] img=rs.getBytes("image");
               ImageIcon image=new ImageIcon(img);
               Image im=image.getImage();
              // Image myImg=im.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_REPLICATE);
              // ImageIcon newImage=new ImageIcon(myImg);
              ImageIcon newImage=new ImageIcon(im);
              jlabel_photo.setIcon(newImage);
           }
           else
           {
               JOptionPane.showMessageDialog(null,"no data");
               
           }
      
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
   
        Date bdate;
         try {
             bdate=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
             jDateChooser1.setDate(bdate);
         } catch (ParseException ex) {
            /// Logger.getLogger(manageStudentForm.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, ex);
         }
       }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    try{ 
          
        FileInputStream fin=null;
        int len = 0;
        String name=jTextField2.getText();
        String fname=jTextField3.getText();
        String mname=jTextField4.getText();
        String par_addres=jTextArea1.getText();
        String cur_addres=jTextArea2.getText();
        String sex="Male";
        String phone=jTextField8.getText();
        Integer sclass=Integer.parseInt(jTextField6.getText());
       Integer id=Integer.parseInt(jTextField1.getText());
        if(jRadioButton2.isSelected())
        {
            sex="Female";
        }
     if(verifyText())
      {
            
        SimpleDateFormat dateForm=new SimpleDateFormat("yyyy-MM-dd");
        String bdate=dateForm.format(jDateChooser1.getDate());
       try {
             try {
                 fin=new FileInputStream(f);
                len=(int)f.length(); 
           } catch (Exception e) {
               /// JOptionPane.showMessageDialog(null,e);
           }
             
           try {
                Connection con=null;
    
//                   try {
//                       Class.forName("com.mysql.jdbc.Driver"); 
//                       con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/highschool?zeroDateTimeBehavior=convertToNull", "root","");
//                      
//                   } catch (ClassNotFoundException ex) {
//                       Logger.getLogger(StudentUpdate.class.getName()).log(Level.SEVERE, null, ex);
//                   }
                 con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/highschool?zeroDateTimeBehavior=convertToNull", "root","");
                 PreparedStatement ps;
                 ps=con.prepareStatement("UPDATE `student_info` SET `name`=?,`father`=?,`mather`=?,`dob`=?,`gender`=?,`class`=?,`phone`=?,`par_address`=?,`cur_address`=?,`image`=? WHERE `id`=?");
                 ps.setString(1, name);
                 ps.setString(2, fname);
                 ps.setString(3,mname);
                 ps.setString(4,bdate);
                 ps.setString(5, sex);
                 ps.setInt(6, sclass);
                 ps.setString(7,phone);
                 ps.setString(8,par_addres);
                 ps.setString(9, cur_addres);
                 ps.setBinaryStream(10, fin, len);
                 ps.setInt(11, id);
                 if(ps.executeUpdate()>0)
                 {
                     JOptionPane.showMessageDialog(null," student data updated");
                 }
                 else
                     JOptionPane.showMessageDialog(null," student data not updated");
            }
                 catch (SQLException ex) {    
                JOptionPane.showMessageDialog(null,"add failed");
                 JOptionPane.showMessageDialog(null,ex);
            }
          StudentUpdate.jTable1.setModel(new DefaultTableModel(null,new Object[]{"id","name","Fname","Mname","Dob","gender","class","phone","par_addr","cur_addr","image"}));
            s.fillStudentJtable(StudentUpdate.jTable1,"");
        
       } catch (HeadlessException ex) {
         JOptionPane.showMessageDialog(null,ex);
//       }    catch (FileNotFoundException ex) {
             JOptionPane.showMessageDialog(null,ex); 
                Logger.getLogger(StudentUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
      
     }
       }
       catch(NumberFormatException e)
       {
////           JOptionPane.showMessageDialog(null, e);
       }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                           StudentClass form=new StudentClass();
                           form.setVisible(true);
                           form.setLocationRelativeTo(null);
//                         form.dispose();
                           form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                           dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                          ManuClass form=new ManuClass();
                           form.setVisible(true);
                           form.setLocationRelativeTo(null);
                          /// form.resize(0, 0);
                          //form.setSize(600,600);
                           ///form.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                           form.welcome.setText("Wecome Mr "+jTextField1.getText());
                           dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TeacherClass form=new  TeacherClass();
        //                         form.setDefaultCloseOperation(null);
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        //                         form.dispose();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ResultClass form=new  ResultClass();
        //                           form.setDefaultCloseOperation(null);
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        //                          form.dispose();
        form.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ManuClass form=new ManuClass();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        /// form.resize(0, 0);
        //form.setSize(600,600);
        ///form.setExtendedState(JFrame.MAXIMIZED_BOTH);
        form.welcome.setText("Wecome Mr "+jTextField1.getText());
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ClassMain form=new ClassMain();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        //                         form.dispose();
        form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
        form.setResizable(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    public boolean verifyText()
         { 
        if(jTextField1.getText().equals("")|| jTextField2.getText().equals("") ||jTextField3.getText().equals("") ||  jTextField4.getText().equals("") || jDateChooser1.getDate()==null || jTextField6.getText().equals("")|| jTextField8.getText().equals("")|| jTextArea1.getText().equals("")||jTextArea2.getText().equals(""))
        {
              JOptionPane.showMessageDialog(null,"one or more emtry field");
               return false;
        }
        /// choose a date higher than the current date
        else if(jDateChooser1.getDate().compareTo(new Date())>0)
        {
            JOptionPane.showMessageDialog(null,"invalid date");
             return false;
        }
      else
        return true;
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static final javax.swing.JButton jButton2 = new javax.swing.JButton();
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel jlabel_photo;
    private JButton btnNewButton;
    private JButton btnNewButton_1;
    private JButton btnNewButton_2;
    // End of variables declaration//GEN-END:variables
}
